###
# (C) Copyright [2020] Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
  - name: Ensure to cleanup ports and services before adding hosts.
    hosts: k8sclusternodes # Ensure that these nodes list in in sync with vars.yml under k8shosts.host_pools section.Otherwise you will have nodes with error state
    gather_facts: false
    roles:
      - role: k8s-hosts
        vars:
          cleanup: yes
  - name: Add k8s-hosts into cluster and install bundle.
    hosts: localhost
    gather_facts: false
    roles:
      - role: k8s-hosts
        vars:
          addhosts: yes

  - name: Delete k8s-hosts from cluster.
    hosts: localhost
    gather_facts: false
    roles:
      - role: k8s-hosts
        vars:
          #deletehosts: yes
          delete_pools:
            - host: 10.1.10.22
